name: PlotBorder
version: ${project.version}
main: de.nononitas.plotborder.PlotBorder
authors: [Nononitas, Fedox]
api-version: 1.21
depend:
  - PlotSquared
commands:
  plotborder:
  rand:
    aliases:
      - border
  wall:
    aliases:
      - wand
